# Generated by Django 4.2.4 on 2023-10-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('family_Id', models.AutoField(primary_key=True, serialize=False)),
                ('member_Count', models.IntegerField()),
                ('dependents_Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('budget_Id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_Name', models.CharField(max_length=50)),
                ('budget_Amount', models.IntegerField()),
                ('budget_Start_Date', models.DateField()),
                ('budget_End_Date', models.DateField()),
                ('family_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.family')),
            ],
        ),
    ]
